### ISSUE TITLE
Internal render resolution ramblings

### ISSUE THREAD

**Issue by gustafla** [Jaso333/bevy_fixed_viewport#1]
Thank you, this plugin is brilliant, it's almost exactly what I needed, and I will be using it for a project.

I'm new to Bevy and I'm sorry for abusing the Issues here, but I'm looking for a way to control the window internal resolution, especially on Wayland with the `wp_viewporter` as SDL2's [mode emulation](https://wiki.libsdl.org/SDL2/SDL_HINT_VIDEO_WAYLAND_MODE_EMULATION) as mentioned [here](https://github.com/libsdl-org/SDL/issues/6438#issuecomment-1288773501).

I know one can set the `primary_window`'s `resolution` and even `resize_constraints` at App initialization, but that does not achieve the desired result, which is to stretch the low resolution window contents to the full window size. When entering fullscreen, the window gets a new inner size, which isn't stretched/upsampled in any way.

The simpler way to achieve a simiar low render resolution would probably be using a [custom render pass](https://bevyengine.org/examples/shaders/custom-post-processing/), but that wastes hardware resources as we can avoid extra copies with the aforementioned wp_viewporter protocol. This extra copying of the rendered image actually makes a difference when doing 3D graphics on low-end devices.

I should probably initiate some other issue or discussion elsewhere, but before doing that, I'm asking if you have any pointers regarding my problem? Feel free to close and ignore this issue if I'm bothering you.

**Comment by gustafla** [comment]
Ah, I found this: https://github.com/bevyengine/bevy/issues/8775

**Comment by Jaso333** [comment]
Glad you were able to find a solution to your problem. I'm also glad you like my plugin, I hope that it gets upstreamed into Bevy one day! I must be honest, I had no idea what your problem was about, so I couldn't have provided a solution anyway!
